spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test_docker2
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update

server:
  port: ${PORT_INTERNAL:8081}